import { createSlice } from "@reduxjs/toolkit";

const getStored = (key) => {
  if (typeof window === "undefined") return null;
  return window.localStorage.getItem(key);
};

const setStored = (key, value) => {
  if (typeof window === "undefined") return;

  if (value) window.localStorage.setItem(key, value);
  else window.localStorage.removeItem(key);
};

//Remember, redux stores minimal state needed for the app , hence it only stores the client side decisions not the actual user or org data fetched from backend. This keeps our state normalized and prevents stale data issues. We can always derive the actual user or org data from the stored ids when needed.

//backend related state are stored in RTK Query cache (see baseApi.js) and accessed via hooks generated by createApi. This way we have a single source of truth for server data and can take advantage of features like caching, automatic refetching, and cache invalidation.

const initialState = {
  accessToken: getStored("accessToken"),
  refreshToken: getStored("refreshToken"),

  // session lifecycle flags (NOT business data)
  isAuthenticated: Boolean(getStored("accessToken")),

  // prevents UI flash before /me finishes
  isInitialized: false,
};

const authSlice = createSlice({
  name: "auth",
  initialState,
  reducers: {
    // called after login or refresh inside baseQuery
    setTokens: (state, action) => {
      const accessToken = action.payload?.accessToken || null;
      const refreshToken = action.payload?.refreshToken || null;

      state.accessToken = accessToken;
      state.refreshToken = refreshToken;
      state.isAuthenticated = true;
      state.isInitialized = true;

      setStored("accessToken", accessToken);
      setStored("refreshToken", refreshToken);
    },

    // called when /me succeeds but no token rotation happened
    markAuthenticated: (state) => {
      state.isAuthenticated = true;
      state.isInitialized = true;
    },

    // called once when app confirms auth status (even guest)
    markInitialized: (state) => {
      state.isInitialized = true;
    },

    clearAuth: (state) => {
      state.accessToken = null;
      state.refreshToken = null;
      state.isAuthenticated = false;
      state.isInitialized = true;

      setStored("accessToken", null);
      setStored("refreshToken", null);
    },

    // // hard logout (manual or refresh failure)
    // logout: (state) => {
    //   Object.assign(state, initialState);
    //   state.isInitialized = true; // prevent auth flicker
    // },

    //we are avoiding usage of logoutreducer in favor of baseApi.util.resetApiState() in authApi.js because it not only resets the auth state but also clears all cached API data, ensuring a clean slate on logout and preventing any potential stale data issues.
    //so it directly talks to server cache
  },
});

export const {
  setTokens,
  markAuthenticated,
  markInitialized,
  clearAuth,
} = authSlice.actions;

export default authSlice.reducer;
